In [1]:
import pandas as pd

In [32]:
data = pd.read_csv("classData.csv")

In [33]:
data

,G,C,B,A,Ia,Ib,Ic,Va,Vb,Vc
0,1,0,0,1,-151.291812,-9.677452,85.800162,0.400750,-0.132935,-0.267815
1,1,0,0,1,-336.186183,-76.283262,18.328897,0.312732,-0.123633,-0.189099
2,1,0,0,1,-502.891583,-174.648023,-80.924663,0.265728,-0.114301,-0.151428
3,1,0,0,1,-593.941905,-217.703359,-124.891924,0.235511,-0.104940,-0.130570
4,1,0,0,1,-643.663617,-224.159427,-132.282815,0.209537,-0.095554,-0.113983
...,...,...,...,...,...,...,...,...,...,...
7856,0,0,0,0,-66.237921,38.457041,24.912239,0.094421,-0.552019,0.457598
7857,0,0,0,0,-65.849493,37.465454,25.515675,0.103778,-0.555186,0.451407
7858,0,0,0,0,-65.446698,36.472055,26.106554,0.113107,-0.558211,0.445104
7859,0,0,0,0,-65.029633,35.477088,26.684731,0.122404,-0.561094,0.438690
7860,0,0,0,0,-64.598401,34.480799,27.250065,0.131669,-0.563835,0.432166

In [34]:
data["Class"] = 2**3 * data["G"] + 2**2 * data["C"]+ 2**1 * data["B"] + 2**0 *data["A"]

In [38]:
data.drop(columns=["G", "C", "B", "A"], inplace=True)

In [39]:
data

              Ia          Ib          Ic        Va        Vb        Vc  Class
0    -151.291812   -9.677452   85.800162  0.400750 -0.132935 -0.267815      9
1    -336.186183  -76.283262   18.328897  0.312732 -0.123633 -0.189099      9
2    -502.891583 -174.648023  -80.924663  0.265728 -0.114301 -0.151428      9
3    -593.941905 -217.703359 -124.891924  0.235511 -0.104940 -0.130570      9
4    -643.663617 -224.159427 -132.282815  0.209537 -0.095554 -0.113983      9
...          ...         ...         ...       ...       ...       ...    ...
7856  -66.237921   38.457041   24.912239  0.094421 -0.552019  0.457598      0
7857  -65.849493   37.465454   25.515675  0.103778 -0.555186  0.451407      0
7858  -65.446698   36.472055   26.106554  0.113107 -0.558211  0.445104      0
7859  -65.029633   35.477088   26.684731  0.122404 -0.561094  0.438690      0
7860  -64.598401   34.480799   27.250065  0.131669 -0.563835  0.432166      0

[7861 rows x 7 columns]

In [29]:
data.to_csv("data_with_class_column.csv")